language: rust
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo doc
  - echo '<html><head><meta http-equiv="refresh" content="0; URL=./webdev_lib"><meta name="keywords" content="automatic redirection"></head></html>' > target/doc/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master

  local_dir: target/doc
